### ISSUE TITLE
Back-end: Signup / Login API Routes

### ISSUE THREAD

**Issue by sina-jamshidi** [hatchways/team-kim-possible#15]
- Create a Register route (POST)
    - this will create a new user, return 201
    - validation on the back-end - password should be atleast 6 characters, required fields (email, name)
    - simple password validation (>6 chars)
- Create a Login route (POST)
    - verify username and password
    - return 4xx if things are incorrect
- User model, don't want to save password directly on the database (hash/salt before we save them)
- Add an auth middleware / decorator - we can easily create authenticated routes and get the user object
- Try to use a decent authentication strategy something like using HTTP only cookies or localstorage

**Comment by alextheprogrammer21** [comment]
Hi Chris, 

Just wanted to update you that I ended up creating a user schema for the database as well as a test user to test the database. It's currently pushed to the feature-mongoDBConnection branch. Thought I'd let you know in case you want use some of the code for your user routes

**Comment by Chris-DJ-Kim** [comment]
Okay, I will check it out!
